select *
from member
ORDER BY MNO DESC;

DROP TABLE TB_FILE;
CREATE TABLE TB_FILE(
    IDX NUMBER,
    PARENT_SEQ NUMBER NOT NULL,
    ORIGINAL_FILE_NAME VARCHAR2(260 BYTE) NOT NULL,
    STORED_FILE_NAME VARCHAR2(36 BYTE) NOT NULL,
    FILE_SIZE NUMBER,
    CRE_DATE DATE NOT NULL,
    PRIMARY KEY(IDX)
);

CREATE SEQUENCE TB_FILE_IDX_SEQ
START WITH 1
INCREMENT BY 1;

DESC TB_FILE;

INSERT INTO TB_FILE
(IDX, PARENT_SEQ, ORIGINAL_FILE_NAME, STORED_FILE_NAME, FILE_SIZE, CRE_DATE)
VALUES(1, 1, '파일명', 'OTHER_FILE', 1024, SYSDATE);

SELECT *
FROM TB_FILE;

ROLLBACK;